### PR TITLE
Configure prettier pre-commit hook and reformat existing files

### PR DESCRIPTION
**Pull request by kenibrewer**
**PR Checklist**

-   [x] A description of the changes is added to the description of this PR.
-   [x] If there is a related issue, make sure it is linked to this PR.
-   [x] If you've fixed a bug or added code that should be tested, add tests!
-   [x] Documentation in `docs` is updated

**Description of changes**

This PR is intended to be merged after #95 . It addresses #96. 

It includes the following changes:
- Adds prettier pre-commit hook for opinionated formatting of markdown 
- Adds an editor-config file to standardize line lengths and indentation style across differing tools
- README.rst in template folder converted to README.md
- All existing markdown adjusted to have a single sentence per line (for easier diffs)
- All existing markdown files reformatted with prettier

### CODE REVIEW

**Comment by fpgmaas** [comment]
Thanks for the contribution @kenibrewer, it looks promising! If it's okay with you, I'll review this one after we have finalized the PR regarding devcontainers to reduce the diff a bit. I just placed one more comment on that PR, I think we can merge after we have handled that!

**Comment by kenibrewer** [comment]
@fpgmaas This is now ready for review. Two of the checks failed, but they succeeded when I [triggered them again](https://github.com/kenibrewer/cookiecutter-poetry/actions/runs/6580417949/job/17878354460?pr=1) by creating a pull request against my fork. I think the issue is probably something due to cache not being invalidated when I force-pushed a rebase to my branch.

**Comment by fpgmaas** [comment]
> @fpgmaas When do you think you'll have a chance to review this PR? I've got some docs changes/improvements I'd like to submit, but the diffs would be pretty complicated if I tried to submit them without this one merged into main.

Hi @kenibrewer, sorry for my relatively slow response! Pull request looks good to me. Am I correct in understanding that the issue. outlined [here](https://github.com/fpgmaas/cookiecutter-poetry/issues/96#issuecomment-1763836268) should not be a problem since we only format indentations and line lengths, and thus there are no issues that can pop-up in our current Jinja templates once they are parsed?

**Comment by kenibrewer** [comment]
@fpgmaas Correct. Prettier is similar to black and it only formats code in ways that doesn't change the functionality. Beyond that, the prettier pre-commit hook for `cookecutter-poetry` [is instructed](https://github.com/fpgmaas/cookiecutter-poetry/blob/dd1b52eadfee0c1a3c8943d402d96a9e1ff776f0/.pre-commit-config.yaml#L20C40-L20C40) to ignore the template directory entirely.

**Pull request merged**
